= Lab 3
+ #table(columns: (auto, auto, auto, auto, auto),
  align: center,
  table.header(..("Reagent Name", "Reqd. PPE", "Critical Safety Hazards", "Reactivity", "Disposal").map(v => [*#v*])),
  [Curcumin], [Standard PPE (gloves, eyewear, lab coat)], [None], [Nonreactive], [Can be disposed of in sink or trash since it is food-safe],
  [Sodium Phosphate], [Standard PPE (gloves, eyewear, lab coat)], [None], [Nonreactive], [Dispose of in sink per SDS since it is diluted],
  [Ethanol], [Standard PPE (gloves, eyewear, lab coat)], [Flammable, Eye irritant, cannot be used near sonicator], [Reactive], [Must be set aside for special disposal]
)
+ A P1000 can technically be used for all quantities in step A2, but it may be preferable to use a P200 for 0.1 mL and 0.2 mL aliquots. For step A3, a P1000 may be used by delivering transfering 1 mL twice, but if a larger micropipette is available, it could be used to deliver the quantity in one transfer with a tolerable loss of precision given that only two significant figures are expected.
+ Curcumin has $pi-pi^*$ chromophores, which are formed from alternating double-single carbon-carbon bonds that resonance delocalized. Its $lambda_max$ is 422 nm and has a molar absorptivity of 55000$" M"^(-1) "cm"^(-1)$ at $lambda_max$. 
+ $frac(10.0" mg", 100.0" mL" ) = frac(10.0" mg", 100.0" mL" ) times frac(1" g", 1000" mg") times frac("1 mol", 368.38" g") times frac("1000 mL", "1 L") times frac("1 M", "1 g/mol")  times frac(10^6 mu" M", "1 M") = 271 mu M$
+ The absorbance for the stock solution at $lambda_max$ can be computed by Beer's law as $A=epsilon_(lambda max) c l = 55000" M"^(-1) "cm"^(-1) times 271 mu"M" times 1" cm"= 15$. The dilution factors for each of the six 10 mL volumetric flasks can be determined by dividing the quantity transferred by the flask volume (10 mL), resulting in 0.01, 0.02, 0.03, 0.04, 0.05, and 0.06 respectively. Since the relationship between absorbance and concentration is proportional, multiplication by the dilution factors yields the absorbances for each of the samples, which are 0.2, 0.3, 0.5, 0.6, 0.8, 0.9 respectively.
+ We can reuse some of our math from the previous problems in order to compute the expected absorbance. In this case, we have 15 mg of sample in a 25 mL flask, which is 1.5 times the mass and 0.25 times the volume of the stock solution in Part A, so the concentration will be 6 times as great before dilution. Dilution occurs with a dilution factor of 0.600 mL/25.0 mL, which means the absorbance of the diluted solution will be 6*0.600 mL/25.0 mL=0.144 times as great as absorbance of the stock solution. Thus the absorbance of the diluted solution can be expected to be no more than 2.16, since that would indicate a pure curcumin sample. It is unlikely that the purity of the commercial sample is this high, which is why we prepared our calibration samples to be between 0.2 and 0.9. Ideally, our sample should fall within that range. 