import os
os.chdir("/home/natetheadequate/working/achem/lab-reports/lab8parta")
# Generated by ChatGPT
import polars as pl
import matplotlib.pyplot as plt
from pathlib import Path

# Get all processed CSV files
input_dir = Path(".")
processed_files = list(input_dir.glob("scanrateadjusted*.csv"))

# Plot each file
for file in processed_files:
    df = pl.read_csv(file)
    plt.figure()
    plt.scatter(df["Potential (V)"], df["Current (A)"] * 1e6, label=file.stem)  # Convert to microamps
    plt.xlabel("Potential (V)")
    plt.ylabel("Current (µA, Baseline Adjusted)")
    plt.title(f"Scan rate {file.stem.replace("scanrateadjusted","")} mV/s")
    plt.legend()
    plt.grid(True)
    plt.savefig(f"{file.stem}.png")  # Save plot as PNG
    plt.close()
