# Generated by ChatGPT
import polars as pl
from pathlib import Path
import os

os.chdir("/home/natetheadequate/working/achem/lab-reports/lab8parta")

# Get all CSV files in the directory
input_dir = Path(".")
csv_files = list(input_dir.glob("*.csv"))

# Group files by scan rate (20, 50, 100)
grouped_files = {}
for file in csv_files:
    name = file.stem  # Remove .csv extension
    if "fescanrate" in name:
        rate = name.replace("fescanrate", "")
        grouped_files[rate] = grouped_files.get(rate, {})
        grouped_files[rate]["fe"] = file
    elif "no3scanrate" in name:
        rate = name.replace("no3scanrate", "")
        grouped_files[rate] = grouped_files.get(rate, {})
        grouped_files[rate]["no3"] = file

# Process each pair
for rate, files in grouped_files.items():
    if "fe" in files and "no3" in files:
        fe_df = pl.read_csv(files["fe"])
        no3_df = pl.read_csv(files["no3"])

        # Compute new columns
        potential_avg = (fe_df["Potential (V)"] + no3_df["Potential (V)"]) / 2
        current_diff = fe_df["Current (A)"] - no3_df["Current (A)"]

        # Create output dataframe
        result_df = pl.DataFrame({
            "Potential (V)": potential_avg,
            "Current (A)": current_diff
        })
        result_df2 = pl.DataFrame({
            "Potential (V)": potential_avg,
            "Current (A)": current_diff * 1e6
        })

        # Save to new CSV
        output_file = input_dir / f"scanrateadjusted{rate}.csv"
        result_df.write_csv(output_file)

        output_file2 = input_dir / f"micro{rate}.csv"
        result_df2.write_csv(output_file2)